name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_call:


jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version: '1.20'

    - run: go get -v -t -d ./...
    - run: go build -v
    - run: go test -test.v -race -cover ./...

  conventional-commits:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - run: pip3 install -U Commitizen
      # The commit hash here is that of the commit where we started using conventional commits.
    - run: cz check --rev-range e6d2233e..HEAD
